// Behavioral anchors per skill, per proficiency level.
// Inspired by SFIA (Skills Framework for the Information Age) methodology.
// Each skill has descriptors for Beginner / Intermediate / Advanced / Expert.

const SKILL_ANCHORS = {
  "Python": {
    beginner:     "Write basic scripts, use variables, loops, and functions. Can run simple programs.",
    intermediate: "Use libraries (pandas, requests), write OOP code, handle exceptions, read/write files.",
    advanced:     "Build production APIs, write efficient algorithms, use async programming and testing frameworks.",
    expert:       "Architect large Python systems, optimize performance, contribute to open-source, mentor others.",
  },
  "JavaScript": {
    beginner:     "Understand variables, DOM manipulation, and basic event listeners in a browser.",
    intermediate: "Work with ES6+, callbacks/promises, fetch API, and build interactive UI components.",
    advanced:     "Design complex async flows, optimize performance, write unit tests, use bundlers (Webpack/Vite).",
    expert:       "Architect large-scale JS applications, deep knowledge of the event loop, engine optimizations.",
  },
  "React": {
    beginner:     "Create basic functional components, understand JSX and props.",
    intermediate: "Use hooks (useState, useEffect), manage state with Context, build multi-page apps with routing.",
    advanced:     "Optimize rendering (memo, useMemo), manage complex global state (Redux/Zustand), write tests.",
    expert:       "Design scalable component architecture, build custom hooks/libraries, lead React codebases.",
  },
  "Node.js": {
    beginner:     "Set up a basic Express server with a few routes.",
    intermediate: "Build REST APIs with middleware, handle authentication, connect to databases.",
    advanced:     "Design microservices, handle streams, optimize async performance, write integration tests.",
    expert:       "Architect high-throughput Node systems, deep knowledge of the event loop and clustering.",
  },
  "SQL": {
    beginner:     "Write SELECT queries with WHERE and basic JOINs on a single table.",
    intermediate: "Write complex JOINs, GROUP BY, subqueries, and basic stored procedures.",
    advanced:     "Optimize queries with indexes, design normalized schemas, write window functions.",
    expert:       "Tune database performance, design sharding strategies, manage replication and transactions.",
  },
  "REST APIs": {
    beginner:     "Understand HTTP verbs (GET/POST), consume an existing API using a tool like Postman.",
    intermediate: "Design and build RESTful endpoints, handle authentication (JWT/OAuth), document with Swagger.",
    advanced:     "Implement versioning, rate limiting, pagination, and error handling best practices.",
    expert:       "Architect API gateways, design API-first systems, define org-wide API standards.",
  },
  "Git": {
    beginner:     "Clone a repo, commit changes, push/pull to GitHub.",
    intermediate: "Create branches, merge, resolve conflicts, use pull requests in a team workflow.",
    advanced:     "Use rebase, cherry-pick, manage complex branching strategies (GitFlow), write CI hooks.",
    expert:       "Design Git workflows for large teams, recover from complex repository issues, audit history.",
  },
  "CSS": {
    beginner:     "Apply basic styles — colors, fonts, margins. Use a CSS framework like Bootstrap.",
    intermediate: "Use Flexbox, Grid, responsive design, and CSS variables for consistent theming.",
    advanced:     "Build complex animations, design systems, and cross-browser compatible layouts from scratch.",
    expert:       "Architect CSS at scale (BEM, CSS-in-JS), optimize rendering performance, define design tokens.",
  },
  "TypeScript": {
    beginner:     "Add basic type annotations to variables and function parameters.",
    intermediate: "Define interfaces, enums, and generics. Migrate a JS project to TypeScript.",
    advanced:     "Use advanced types (conditional, mapped, template literals), configure tsconfig for strict safety.",
    expert:       "Design complex type systems, write utility type libraries, enforce types across large codebases.",
  },
  "Docker": {
    beginner:     "Run pre-built Docker images, understand containers vs VMs.",
    intermediate: "Write Dockerfiles, build and tag images, use docker-compose for multi-container apps.",
    advanced:     "Optimize image layers, manage volumes and networks, integrate Docker into CI/CD pipelines.",
    expert:       "Design container strategies for production, manage image security scanning and registries.",
  },
  "Machine Learning": {
    beginner:     "Understand supervised vs unsupervised learning concepts. Run a tutorial model in scikit-learn.",
    intermediate: "Train and evaluate classification/regression models, handle preprocessing and cross-validation.",
    advanced:     "Select and tune models systematically, handle imbalanced data, explain model decisions (SHAP).",
    expert:       "Design end-to-end ML systems, publish research-level results, lead ML teams.",
  },
  "Statistics": {
    beginner:     "Understand mean, median, standard deviation, and basic probability.",
    intermediate: "Apply hypothesis testing, confidence intervals, correlation, and regression analysis.",
    advanced:     "Use Bayesian inference, experimental design (A/B testing), multivariate analysis.",
    expert:       "Derive statistical models from first principles, lead quantitative research programs.",
  },
  "Data Visualization": {
    beginner:     "Create basic bar/line charts using Excel or a library like matplotlib.",
    intermediate: "Build interactive dashboards with Plotly, Seaborn, or Tableau. Choose appropriate chart types.",
    advanced:     "Design data stories that drive decisions, build reusable visualization components.",
    expert:       "Create bespoke visualizations for complex datasets, define organization-wide BI standards.",
  },
  "Pandas": {
    beginner:     "Load a CSV into a DataFrame, filter rows, and inspect data with head/describe.",
    intermediate: "Group, merge, pivot, and reshape DataFrames. Handle missing values and data types.",
    advanced:     "Optimize performance with vectorized operations, use MultiIndex, process large files efficiently.",
    expert:       "Build pandas-based data pipelines at scale, extend pandas with custom accessors.",
  },
  "Deep Learning": {
    beginner:     "Understand neurons, layers, and activation functions. Run a pre-built neural network tutorial.",
    intermediate: "Build and train CNNs/RNNs with Keras/PyTorch. Understand backpropagation and regularization.",
    advanced:     "Design custom architectures, implement attention mechanisms, train on GPUs with mixed precision.",
    expert:       "Invent novel architectures, reproduce state-of-the-art papers, lead deep learning research.",
  },
  "Feature Engineering": {
    beginner:     "Create simple derived features (ratios, date parts) from existing columns.",
    intermediate: "Encode categoricals, scale numerics, handle missing values, build feature pipelines.",
    advanced:     "Design domain-specific features, use target encoding, apply feature selection techniques.",
    expert:       "Systematically discover high-value features, build automated feature generation systems.",
  },
  "Big Data": {
    beginner:     "Understand why traditional tools fail at scale. Aware of Hadoop and Spark concepts.",
    intermediate: "Write Spark jobs in Python/Scala, query with Hive/SparkSQL on distributed datasets.",
    advanced:     "Optimize Spark jobs (partitioning, caching), design data lake architectures.",
    expert:       "Architect petabyte-scale data platforms, optimize cluster performance, define data engineering standards.",
  },
  "Kubernetes": {
    beginner:     "Understand pods, services, and deployments. Can deploy a pre-written manifest.",
    intermediate: "Write YAML manifests, manage ConfigMaps/Secrets, scale deployments, use kubectl fluently.",
    advanced:     "Configure Ingress, RBAC, Helm charts, HPA, and set up monitoring with Prometheus.",
    expert:       "Design multi-cluster strategies, implement custom operators, optimize cluster resource usage.",
  },
  "Linux": {
    beginner:     "Navigate the filesystem, run basic commands (ls, cd, cp, grep).",
    intermediate: "Write shell scripts, manage processes, configure services with systemd, use SSH.",
    advanced:     "Tune kernel parameters, manage users/permissions at scale, troubleshoot system performance.",
    expert:       "Deep kernel knowledge, write custom system-level tools, harden and audit production servers.",
  },
  "CI/CD": {
    beginner:     "Understand the concept of automated pipelines. Can read an existing GitHub Actions workflow.",
    intermediate: "Build pipelines that lint, test, build, and deploy automatically (GitHub Actions, GitLab CI).",
    advanced:     "Design multi-stage pipelines with rollback, canary deploys, secrets management, and notifications.",
    expert:       "Architect CI/CD platforms for entire engineering organizations, define deployment standards.",
  },
  "AWS": {
    beginner:     "Use the AWS console to launch an EC2 instance or S3 bucket.",
    intermediate: "Deploy apps using EC2, S3, RDS, Lambda. Understand IAM roles and VPC basics.",
    advanced:     "Design fault-tolerant architectures with auto-scaling, CloudFormation/CDK, and cost optimization.",
    expert:       "Architect enterprise AWS solutions, hold Solutions Architect Professional certification level.",
  },
  "Terraform": {
    beginner:     "Understand Infrastructure as Code concepts. Can read a basic .tf file.",
    intermediate: "Write modules to provision cloud resources, manage state files, use variables and outputs.",
    advanced:     "Design reusable module libraries, manage remote state, implement policy-as-code (Sentinel).",
    expert:       "Architect large-scale multi-cloud IaC platforms, mentor teams on Terraform best practices.",
  },
  "Networking": {
    beginner:     "Understand TCP/IP, DNS, HTTP/HTTPS basics and how data travels between computers.",
    intermediate: "Configure VLANs, subnets, firewalls. Troubleshoot connectivity with ping, traceroute, Wireshark.",
    advanced:     "Design network architectures for security and performance, implement VPNs and load balancers.",
    expert:       "Architect enterprise network infrastructure, deep protocol knowledge, lead network security audits.",
  },
  "Monitoring": {
    beginner:     "View existing dashboards in Grafana or Datadog. Understand what metrics and logs are.",
    intermediate: "Set up Prometheus + Grafana, create alerts, instrument applications with custom metrics.",
    advanced:     "Design observability strategy (metrics, logs, traces), implement SLOs and error budgets.",
    expert:       "Build organization-wide observability platforms, define incident response frameworks.",
  },
  "Ethical Hacking": {
    beginner:     "Understand common attack types (SQLi, XSS, phishing). Familiar with the OWASP Top 10.",
    intermediate: "Use tools like Nmap, Burp Suite, Metasploit for guided penetration tests.",
    advanced:     "Conduct independent penetration tests, write CVE-quality vulnerability reports.",
    expert:       "Lead red team operations, discover zero-days, design org-wide penetration testing programs.",
  },
  "Cryptography": {
    beginner:     "Understand symmetric vs asymmetric encryption, hashing, and what TLS does.",
    intermediate: "Implement encryption in code (AES, RSA), understand PKI, certificates, and key management.",
    advanced:     "Design cryptographic protocols, audit implementations for weaknesses, understand side-channel attacks.",
    expert:       "Conduct cryptanalysis, design novel cryptographic schemes, publish security research.",
  },
  "Incident Response": {
    beginner:     "Know the phases of incident response (Prepare, Detect, Contain, Eradicate, Recover).",
    intermediate: "Execute an incident response playbook, collect and preserve evidence, write incident reports.",
    advanced:     "Lead incident response for complex breaches, perform forensic analysis, coordinate across teams.",
    expert:       "Design IR programs from scratch, train response teams, lead post-mortems and regulatory reporting.",
  },
  "SIEM Tools": {
    beginner:     "Understand what a SIEM does. Can view and filter events in Splunk or IBM QRadar.",
    intermediate: "Write correlation rules, create dashboards, tune alerts to reduce false positives.",
    advanced:     "Design SIEM architectures, integrate log sources, build threat detection use cases.",
    expert:       "Architect enterprise SIEM platforms, develop advanced threat hunting methodologies.",
  },
  "Risk Assessment": {
    beginner:     "Identify basic assets and threats. Complete a guided risk assessment template.",
    intermediate: "Quantify risk likelihood and impact, produce risk registers, recommend mitigations.",
    advanced:     "Lead risk assessments for complex systems, align findings to frameworks (ISO 27001, NIST).",
    expert:       "Design enterprise risk management programs, advise C-suite, present to regulators.",
  },
  "Firewalls": {
    beginner:     "Understand what a firewall does. Can view existing rules in a GUI.",
    intermediate: "Configure stateful firewall rules, manage allow/deny lists, review logs for anomalies.",
    advanced:     "Design layered firewall architectures (perimeter, internal, WAF), implement zero-trust rules.",
    expert:       "Architect next-gen firewall strategies for large enterprises, lead firewall audit programs.",
  },
  "Compliance": {
    beginner:     "Aware of major frameworks like GDPR, ISO 27001, SOC 2 and what they cover.",
    intermediate: "Map controls to framework requirements, contribute to audits, maintain compliance documentation.",
    advanced:     "Lead compliance programs, manage third-party audits, identify and close control gaps.",
    expert:       "Design enterprise compliance strategies across multiple frameworks, advise on regulatory changes.",
  },
  "TensorFlow/PyTorch": {
    beginner:     "Run a pre-built model from a tutorial. Understand tensors and basic operations.",
    intermediate: "Build and train custom neural networks, use autograd, load datasets with DataLoaders.",
    advanced:     "Implement custom layers/losses, use distributed training, deploy models with TorchServe/TF Serving.",
    expert:       "Contribute to framework internals, design training infrastructure for large-scale models.",
  },
  "Mathematics": {
    beginner:     "Comfortable with algebra and basic calculus. Understand what a derivative represents.",
    intermediate: "Apply linear algebra (matrix ops, eigenvalues), multivariate calculus, and probability theory.",
    advanced:     "Use optimization theory, information theory, and numerical methods to analyze ML algorithms.",
    expert:       "Derive novel mathematical results, contribute to theoretical ML research publications.",
  },
  "Data Processing": {
    beginner:     "Load, clean, and filter a dataset. Handle basic missing values and format conversions.",
    intermediate: "Build reusable ETL pipelines, validate data quality, handle schema changes.",
    advanced:     "Design scalable data processing systems, implement streaming pipelines (Kafka, Flink).",
    expert:       "Architect real-time + batch data platforms at petabyte scale, define data engineering standards.",
  },
  "MLOps": {
    beginner:     "Understand what MLOps is. Can version a model with MLflow.",
    intermediate: "Build automated training pipelines, track experiments, deploy models behind an API.",
    advanced:     "Implement model monitoring, drift detection, A/B testing for models, use Kubeflow/SageMaker.",
    expert:       "Design ML platform infrastructure for multiple teams, define model governance policies.",
  },
  "Cloud Platforms": {
    beginner:     "Deploy a simple app or notebook on a cloud platform (AWS, GCP, or Azure).",
    intermediate: "Use managed ML services (SageMaker, Vertex AI), set up cloud storage and compute.",
    advanced:     "Design cloud-native ML architectures, optimize cost, implement security best practices.",
    expert:       "Architect multi-cloud AI platforms, hold advanced cloud certifications, lead cloud strategy.",
  },
  "Product Strategy": {
    beginner:     "Understand the concept of a product vision and roadmap. Can articulate user problems.",
    intermediate: "Define product goals with OKRs, prioritize a backlog, align features to business outcomes.",
    advanced:     "Develop market strategy, make build/buy/partner decisions, influence engineering roadmaps.",
    expert:       "Define multi-year product vision, lead strategy across product lines, advise at board level.",
  },
  "Agile/Scrum": {
    beginner:     "Understand sprints, standups, and the basic Scrum framework.",
    intermediate: "Facilitate sprint ceremonies, maintain a healthy backlog, track velocity and burndown.",
    advanced:     "Coach teams on agile practices, scale agile across multiple teams (SAFe, LeSS).",
    expert:       "Transform engineering cultures to agile, define agile standards across an organization.",
  },
  "Data Analysis": {
    beginner:     "Summarize data with basic charts and descriptive stats in Excel or Google Sheets.",
    intermediate: "Use SQL or Python to answer business questions, identify trends, and present findings clearly.",
    advanced:     "Design A/B tests, build self-service analytics tools, translate data into strategic recommendations.",
    expert:       "Build org-wide analytics functions, define data strategy, influence product decisions with data.",
  },
  "Communication": {
    beginner:     "Express ideas clearly in writing and speech in 1:1 settings.",
    intermediate: "Present findings to small groups, write structured documents, adapt style for the audience.",
    advanced:     "Influence decisions through storytelling, present to senior leadership, write executive summaries.",
    expert:       "Communicate complex strategy to all audiences including boards, define comms culture.",
  },
  "User Research": {
    beginner:     "Conduct a simple user interview using a prepared script.",
    intermediate: "Design research plans, run usability tests, synthesize findings into actionable insights.",
    advanced:     "Lead mixed-methods research programs, connect user insights to product strategy.",
    expert:       "Build user research functions, define research methodologies, influence org-wide user-centricity.",
  },
  "Roadmapping": {
    beginner:     "Understand what a product roadmap is and how it connects to strategy.",
    intermediate: "Create and maintain a roadmap in a tool like Jira or Productboard, communicate trade-offs.",
    advanced:     "Build cross-functional roadmaps that balance tech debt, features, and business goals.",
    expert:       "Define multi-year roadmaps across portfolios, align executive teams on strategic direction.",
  },
  "Stakeholder Management": {
    beginner:     "Identify key stakeholders and communicate project status updates.",
    intermediate: "Manage competing priorities, negotiate scope, build trust with cross-functional partners.",
    advanced:     "Align senior stakeholders on strategy, resolve organizational conflicts, influence without authority.",
    expert:       "Build executive relationships at C-suite level, navigate complex political landscapes.",
  },
  "Market Research": {
    beginner:     "Conduct basic competitor analysis using public sources.",
    intermediate: "Run customer surveys, analyze market size (TAM/SAM/SOM), produce research reports.",
    advanced:     "Design primary research programs, synthesize market signals into strategic insights.",
    expert:       "Define market intelligence functions, identify whitespace opportunities, advise on M&A strategy.",
  },
  "Leadership": {
    beginner:     "Take ownership of small tasks, support teammates, and communicate proactively.",
    intermediate: "Lead a small project or team, set clear goals, provide constructive feedback.",
    advanced:     "Build and develop high-performing teams, define team culture, navigate org-level challenges.",
    expert:       "Lead large organizations, define company culture, develop future leaders.",
  },
};

export default SKILL_ANCHORS;
